# Generated by Django 6.0.5 on 2026-08-06 10:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout', models.JSONField(default=dict)),
                ('theme', models.CharField(default='light', max_length=20)),
                ('default_view', models.CharField(default='grid', max_length=50)),
                ('refresh_interval', models.PositiveIntegerField(default=300)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_preferences',
            },
        ),
        migrations.CreateModel(
            name='DashboardActivityFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('article_created', 'Article Created'), ('article_published', 'Article Published'), ('comment_received', 'Comment Received'), ('ad_clicked', 'Ad Clicked'), ('user_registered', 'User Registered'), ('ad_purchased', 'Ad Purchased'), ('subscriber_added', 'Subscriber Added')], max_length=20)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_feed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_activity_feed',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='dashboard_a_user_id_b4ee79_idx'), models.Index(fields=['created_at'], name='dashboard_a_created_30ef36_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('article_count', 'Article Count'), ('view_count', 'View Count'), ('comment_count', 'Comment Count'), ('ad_revenue', 'Ad Revenue'), ('user_growth', 'User Growth'), ('engagement_rate', 'Engagement Rate'), ('bounce_rate', 'Bounce Rate'), ('conversion_rate', 'Conversion Rate')], max_length=20)),
                ('value', models.FloatField(default=0)),
                ('previous_value', models.FloatField(default=0)),
                ('change_percentage', models.FloatField(default=0)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_metrics',
                'ordering': ['-date'],
                'unique_together': {('user', 'metric_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('statistics', 'Statistics'), ('chart', 'Chart'), ('recent_activity', 'Recent Activity'), ('recent_articles', 'Recent Articles'), ('pending_comments', 'Pending Comments'), ('ad_performance', 'Ad Performance'), ('quick_actions', 'Quick Actions'), ('news_feed', 'News Feed'), ('calendar', 'Calendar'), ('custom', 'Custom')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
                ('column', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('width', models.PositiveIntegerField(default=12, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(12)])),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_widgets',
                'ordering': ['column', 'position'],
                'unique_together': {('user', 'widget_type', 'column')},
            },
        ),
        migrations.CreateModel(
            name='QuickAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quick_actions',
                'ordering': ['order'],
                'unique_together': {('user', 'url')},
            },
        ),
    ]
