# Generated by Django 6.0.5 on 2026-08-02 08:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'permissions': [('can_publish_articles', 'Can publish articles'), ('can_manage_users', 'Can manage users'), ('can_moderate_comments', 'Can moderate comments'), ('can_manage_ads', 'Can manage advertisements'), ('can_view_analytics', 'Can view analytics'), ('can_manage_settings', 'Can manage site settings'), ('can_manage_media', 'Can manage media files'), ('can_manage_newsletter', 'Can manage newsletter')]},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('publish', 'Publish'), ('view', 'View'), ('comment', 'Comment'), ('share', 'Share'), ('download', 'Download'), ('subscribe', 'Subscribe'), ('unsubscribe', 'Unsubscribe'), ('password_change', 'Password Change'), ('profile_update', 'Profile Update'), ('article_created', 'Article Created'), ('article_updated', 'Article Updated'), ('article_deleted', 'Article Deleted')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['model_name', 'object_id'], name='user_activi_model_n_2d3ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='user_profil_user_id_fbe33d_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['country'], name='user_profil_country_62f4a9_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_verified'], name='user_profil_is_veri_0e3ed5_idx'),
        ),
    ]
