# Generated by Django 6.0.5 on 2026-08-01 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name (e.g., Election, Economy, World Cup)', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the tag name', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the tag', max_length=300)),
                ('color', models.CharField(blank=True, help_text='Hex color code for the tag', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tag is active and visible')),
                ('article_count', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='tags_slug_c72f9b_idx'), models.Index(fields=['is_active'], name='tags_is_acti_f35278_idx')],
            },
        ),
    ]
