# Generated by Django 6.0.5 on 2026-08-08 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', 'General'), ('appearance', 'Appearance'), ('seo', 'SEO'), ('email', 'Email'), ('social_media', 'Social Media'), ('advertisement', 'Advertisement'), ('security', 'Security'), ('performance', 'Performance'), ('integration', 'Integration')], max_length=20)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_encrypted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'site_settings',
                'ordering': ['category', 'key'],
                'indexes': [models.Index(fields=['category'], name='site_settin_categor_88e0fa_idx'), models.Index(fields=['key'], name='site_settin_key_a6dcbf_idx')],
            },
        ),
        migrations.CreateModel(
            name='ThemeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_global', models.BooleanField(default=False)),
                ('primary_color', models.CharField(default='#007bff', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7)),
                ('success_color', models.CharField(default='#28a745', max_length=7)),
                ('danger_color', models.CharField(default='#dc3545', max_length=7)),
                ('warning_color', models.CharField(default='#ffc107', max_length=7)),
                ('info_color', models.CharField(default='#17a2b8', max_length=7)),
                ('light_color', models.CharField(default='#f8f9fa', max_length=7)),
                ('dark_color', models.CharField(default='#343a40', max_length=7)),
                ('font_family', models.CharField(default='system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif', max_length=100)),
                ('font_size', models.CharField(default='16px', max_length=10)),
                ('layout', models.CharField(choices=[('boxed', 'Boxed'), ('full_width', 'Full Width')], default='full_width', max_length=20)),
                ('sidebar_position', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=20)),
                ('custom_css', models.TextField(blank=True)),
                ('custom_js', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'theme_settings',
            },
        ),
    ]
