# Generated by Django 6.0.5 on 2026-08-01 10:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Politics, Business, Sports)', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the category name', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the category', max_length=500)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class (e.g., fa-gavel for Politics)', max_length=50)),
                ('color', models.CharField(blank=True, help_text='Hex color code for the category (e.g., #FF0000)', max_length=7)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in navigation')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active and visible')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether to show this category in featured sections')),
                ('seo_title', models.CharField(blank=True, max_length=150)),
                ('seo_description', models.CharField(blank=True, max_length=200)),
                ('seo_keywords', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Category image for featured sections', null=True, upload_to='categories/%Y/%m/')),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('article_count', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category if this is a sub-category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='categories_slug_b4303a_idx'), models.Index(fields=['parent', 'is_active'], name='categories_parent__c20446_idx'), models.Index(fields=['order'], name='categories_order_4379ff_idx')],
            },
        ),
    ]
