# Generated by Django 6.0.5 on 2026-08-08 09:16

import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a compelling title for your article', max_length=300, validators=[django.core.validators.MinLengthValidator(5)])),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of the title', max_length=350, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='A short summary of the article. Leave blank to auto-generate from content.', max_length=500)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Write your article content here')),
                ('featured_image', models.ImageField(blank=True, help_text='Main image for the article', null=True, upload_to='articles/%Y/%m/%d/')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Alternative text for the featured image', max_length=200)),
                ('featured_image_caption', models.CharField(blank=True, help_text='Caption for the featured image', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('published', 'Published'), ('scheduled', 'Scheduled'), ('archived', 'Archived'), ('trash', 'Trash')], default='draft', max_length=20)),
                ('publish_option', models.CharField(choices=[('publish_now', 'Publish Now'), ('schedule', 'Schedule')], default='publish_now', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('bookmarks_count', models.PositiveIntegerField(default=0)),
                ('reading_time', models.PositiveSmallIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_order', models.PositiveIntegerField(default=0)),
                ('is_breaking', models.BooleanField(default=False)),
                ('is_exclusive', models.BooleanField(default=False)),
                ('is_editor_pick', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, max_length=150)),
                ('seo_description', models.CharField(blank=True, max_length=200)),
                ('seo_keywords', models.CharField(blank=True, max_length=200)),
                ('canonical_url', models.URLField(blank=True)),
                ('custom_css', models.TextField(blank=True)),
                ('custom_js', models.TextField(blank=True)),
                ('extra_meta', models.JSONField(blank=True, default=dict)),
                ('meta_description', models.TextField(blank=True, max_length=300)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('reference_url', models.URLField(blank=True)),
                ('reference_text', models.CharField(blank=True, max_length=200)),
                ('author', models.ForeignKey(help_text='Author of the article', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Primary category for the article', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='categories.category')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags to categorize the article', related_name='articles', to='tags.tag')),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-published_at', '-created_at'],
                'permissions': [('can_publish_article', 'Can publish articles'), ('can_edit_any_article', 'Can edit any article'), ('can_delete_any_article', 'Can delete any article'), ('can_feature_articles', 'Can feature articles')],
            },
        ),
        migrations.CreateModel(
            name='ArticleSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='articles.article')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'article_schedules',
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ArticleStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_today', models.PositiveIntegerField(default=0)),
                ('views_week', models.PositiveIntegerField(default=0)),
                ('views_month', models.PositiveIntegerField(default=0)),
                ('views_year', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('avg_reading_time', models.FloatField(default=0)),
                ('bounce_rate', models.FloatField(default=0)),
                ('twitter_shares', models.PositiveIntegerField(default=0)),
                ('facebook_shares', models.PositiveIntegerField(default=0)),
                ('linkedin_shares', models.PositiveIntegerField(default=0)),
                ('whatsapp_shares', models.PositiveIntegerField(default=0)),
                ('click_through_rate', models.FloatField(default=0)),
                ('conversion_rate', models.FloatField(default=0)),
                ('engagement_score', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='articles.article')),
            ],
            options={
                'db_table': 'article_statistics',
            },
        ),
        migrations.CreateModel(
            name='RelatedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relations', to='articles.article')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_relations', to='articles.article')),
            ],
            options={
                'db_table': 'related_articles',
                'ordering': ['order'],
                'unique_together': {('source', 'target')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='related_articles',
            field=models.ManyToManyField(blank=True, through='articles.RelatedArticle', to='articles.article'),
        ),
        migrations.CreateModel(
            name='ArticleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, max_length=500)),
                ('slug', models.SlugField(max_length=350)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('change_notes', models.TextField(blank=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='articles.article')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'article_versions',
                'ordering': ['-version_number'],
                'unique_together': {('article', 'version_number')},
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', 'published_at'], name='articles_status_35ee01_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='articles_slug_c8b0c2_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author', 'status'], name='articles_author__b3f50e_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'status'], name='articles_categor_ae22a5_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_featured', 'featured_order'], name='articles_is_feat_95a066_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_breaking'], name='articles_is_brea_b8c29b_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['created_at'], name='articles_created_82e966_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['views_count'], name='articles_views_c_f4bde2_idx'),
        ),
    ]
