# Generated by Django 6.0.5 on 2026-08-31 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload an image for the article', upload_to='article_images/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, help_text="Photo caption - describes what's in the image", max_length=500)),
                ('byline', models.CharField(blank=True, help_text="Photographer or image source credit (e.g., 'Photo by John Doe')", max_length=200)),
                ('is_featured', models.BooleanField(default=False, help_text='Set as the main/featured image for this article')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility and SEO', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.article')),
            ],
            options={
                'db_table': 'article_images',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['article', 'is_featured'], name='article_ima_article_9dc654_idx'), models.Index(fields=['article', 'order'], name='article_ima_article_866772_idx')],
            },
        ),
    ]
