# Generated by Django 6.0.5 on 2026-08-01 10:41

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('categories', '0001_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Email subject line', max_length=200)),
                ('preview_text', models.CharField(blank=True, help_text='Preview text shown in email clients', max_length=200)),
                ('content', ckeditor.fields.RichTextField(help_text='Email content - HTML supported')),
                ('plain_text', models.TextField(blank=True, help_text='Plain text version of the email')),
                ('template', models.CharField(choices=[('default', 'Default'), ('minimal', 'Minimal'), ('featured', 'Featured'), ('digest', 'Digest'), ('custom', 'Custom')], default='default', max_length=20)),
                ('template_custom', models.TextField(blank=True, help_text='Custom HTML template')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('subscribers_count', models.PositiveIntegerField(default=0)),
                ('opens_count', models.PositiveIntegerField(default=0)),
                ('clicks_count', models.PositiveIntegerField(default=0)),
                ('unsubscribe_count', models.PositiveIntegerField(default=0)),
                ('bounce_count', models.PositiveIntegerField(default=0)),
                ('spam_reports', models.PositiveIntegerField(default=0)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=200)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('articles', models.ManyToManyField(blank=True, help_text='Articles to include in this newsletter', related_name='newsletters', to='articles.article')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_newsletters', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_newsletters', to=settings.AUTH_USER_MODEL)),
                ('target_categories', models.ManyToManyField(blank=True, help_text='Send only to subscribers of these categories', related_name='newsletters', to='categories.category')),
            ],
            options={
                'db_table': 'newsletters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="Subscriber's email address", max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('name', models.CharField(blank=True, help_text="Subscriber's full name", max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('spam', 'Marked as Spam')], default='active', max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('instant', 'Instant')], default='daily', help_text='How often to send newsletters', max_length=20)),
                ('confirmation_token', models.CharField(blank=True, max_length=100)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('opens', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('unsubscribes', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(blank=True, help_text='Where this subscriber came from (e.g., website, social media, manual)', max_length=100)),
                ('source_url', models.URLField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('last_opened', models.DateTimeField(blank=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, help_text='Categories this subscriber wants to receive', related_name='subscribers', to='categories.category')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags this subscriber wants to receive', related_name='subscribers', to='tags.tag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscribers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('open', 'Opened'), ('click', 'Clicked'), ('unsubscribe', 'Unsubscribed'), ('bounce', 'Bounced'), ('spam', 'Marked as Spam')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True)),
                ('link', models.URLField(blank=True, help_text="Link clicked (if action is 'click')")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='newsletter.newsletter')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='newsletter.subscriber')),
            ],
            options={
                'db_table': 'newsletter_tracking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['status', 'scheduled_for'], name='newsletters_status_12b0a8_idx'),
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['created_by'], name='newsletters_created_039f31_idx'),
        ),
        migrations.AddIndex(
            model_name='newsletter',
            index=models.Index(fields=['sent_at'], name='newsletters_sent_at_ffadea_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['email'], name='subscribers_email_9c2a5b_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['status'], name='subscribers_status_4a8136_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['created_at'], name='subscribers_created_d14985_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['frequency', 'status'], name='subscribers_frequen_9c8aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettertracking',
            index=models.Index(fields=['newsletter', 'action'], name='newsletter__newslet_a00c18_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettertracking',
            index=models.Index(fields=['subscriber'], name='newsletter__subscri_209baa_idx'),
        ),
        migrations.AddIndex(
            model_name='newslettertracking',
            index=models.Index(fields=['created_at'], name='newsletter__created_7e202d_idx'),
        ),
    ]
