# Generated by Django 6.0.5 on 2026-08-08 09:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ad title for internal reference', max_length=200)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(help_text='Ad image (supported formats: JPG, PNG, GIF, WEBP)', upload_to='ads/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('video_url', models.URLField(blank=True, help_text='URL for video ads')),
                ('link_url', models.URLField(help_text='URL users go to when clicking the ad')),
                ('link_target', models.CharField(choices=[('_self', 'Same Window'), ('_blank', 'New Window')], default='_blank', max_length=10)),
                ('position', models.CharField(choices=[('header', 'Header Banner'), ('sidebar', 'Sidebar'), ('in_article', 'In-Article'), ('between_posts', 'Between Posts'), ('footer', 'Footer'), ('featured_section', 'Featured Section'), ('popup', 'Popup'), ('video', 'Video Ad'), ('sponsored', 'Sponsored Content')], max_length=20)),
                ('size', models.CharField(choices=[('leaderboard', '728x90 - Leaderboard'), ('banner', '468x60 - Banner'), ('half_banner', '234x60 - Half Banner'), ('square', '250x250 - Square'), ('small_square', '200x200 - Small Square'), ('button', '125x125 - Button'), ('medium_rectangle', '300x250 - Medium Rectangle'), ('large_rectangle', '336x280 - Large Rectangle'), ('skyscraper', '120x600 - Skyscraper'), ('wide_skyscraper', '160x600 - Wide Skyscraper'), ('half_page', '300x600 - Half Page')], max_length=20)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField(help_text='When the ad should start showing')),
                ('end_date', models.DateTimeField(help_text='When the ad should stop showing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Approval'), ('scheduled', 'Scheduled'), ('paused', 'Paused'), ('expired', 'Expired'), ('rejected', 'Rejected'), ('draft', 'Draft')], default='pending', max_length=20)),
                ('target_countries', models.JSONField(blank=True, default=list)),
                ('target_cities', models.JSONField(blank=True, default=list)),
                ('budget', models.DecimalField(decimal_places=2, default=0, help_text='Total budget for this ad campaign', max_digits=10)),
                ('cost_per_click', models.DecimalField(decimal_places=2, default=0, help_text='Cost per click (CPC)', max_digits=10)),
                ('cost_per_impression', models.DecimalField(decimal_places=2, default=0, help_text='Cost per 1000 impressions (CPM)', max_digits=10)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('clicks_count', models.PositiveIntegerField(default=0)),
                ('unique_views', models.PositiveIntegerField(default=0)),
                ('unique_clicks', models.PositiveIntegerField(default=0)),
                ('conversion_count', models.PositiveIntegerField(default=0)),
                ('max_clicks', models.PositiveIntegerField(default=0, help_text='Maximum number of clicks (0 for unlimited)')),
                ('max_impressions', models.PositiveIntegerField(default=0, help_text='Maximum number of impressions (0 for unlimited)')),
                ('daily_limit', models.PositiveIntegerField(default=0, help_text='Daily impression limit (0 for unlimited)')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority ads show first (0-100)')),
                ('advertiser', models.ForeignKey(help_text='Advertiser who owns this ad', on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL)),
                ('targeted_articles', models.ManyToManyField(blank=True, help_text='Show ad only on these specific articles', related_name='ads', to='articles.article')),
                ('targeted_categories', models.ManyToManyField(blank=True, help_text='Show ad only on these categories (leave blank for all)', related_name='ads', to='categories.category')),
            ],
            options={
                'db_table': 'advertisements',
                'ordering': ['-priority', 'views_count'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='advertisements.advertisement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ad_clicks',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='advertisements.advertisement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ad_views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['position', 'status'], name='advertiseme_positio_18f67d_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['start_date', 'end_date'], name='advertiseme_start_d_fe9acd_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['advertiser', 'status'], name='advertiseme_adverti_06fdb5_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['priority', 'views_count'], name='advertiseme_priorit_087c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisementclick',
            index=models.Index(fields=['ad', 'clicked_at'], name='ad_clicks_ad_id_c2e502_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisementclick',
            index=models.Index(fields=['session_id'], name='ad_clicks_session_9d6280_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisementview',
            index=models.Index(fields=['ad', 'viewed_at'], name='ad_views_ad_id_f4a3c1_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisementview',
            index=models.Index(fields=['session_id'], name='ad_views_session_60d897_idx'),
        ),
    ]
