# Generated by Django 6.0.5 on 2026-08-08 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsTrafficSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('direct', 'Direct'), ('search', 'Search Engine'), ('social', 'Social Media'), ('referral', 'Referral'), ('email', 'Email'), ('ad', 'Advertisement'), ('other', 'Other')], max_length=20)),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True)),
                ('visits', models.PositiveIntegerField(default=0)),
                ('unique_visits', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'analytics_traffic_sources',
                'indexes': [models.Index(fields=['date'], name='analytics_t_date_f4253a_idx'), models.Index(fields=['source_type'], name='analytics_t_source__3977d2_idx')],
                'unique_together': {('source_type', 'source_name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('article_view', 'Article View'), ('click', 'Click'), ('scroll', 'Scroll'), ('time_on_page', 'Time on Page'), ('conversion', 'Conversion'), ('download', 'Download'), ('search', 'Search')], max_length=20)),
                ('event_name', models.CharField(blank=True, max_length=100)),
                ('event_value', models.FloatField(blank=True, null=True)),
                ('url', models.URLField()),
                ('path', models.CharField(max_length=500)),
                ('referer', models.URLField(blank=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('user_agent', models.TextField(blank=True)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('browser_version', models.CharField(blank=True, max_length=20)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('os_version', models.CharField(blank=True, max_length=20)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('device_brand', models.CharField(blank=True, max_length=50)),
                ('device_model', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_e_event_t_c3dcde_idx'), models.Index(fields=['url'], name='analytics_e_url_320d43_idx'), models.Index(fields=['user', 'created_at'], name='analytics_e_user_id_7e4ee5_idx'), models.Index(fields=['session_id'], name='analytics_e_session_b3cbf5_idx'), models.Index(fields=['ip_address'], name='analytics_e_ip_addr_327ff6_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsPageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('path', models.CharField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('views', models.PositiveIntegerField(default=0)),
                ('unique_views', models.PositiveIntegerField(default=0)),
                ('avg_time_on_page', models.FloatField(default=0)),
                ('bounce_count', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_views', to='articles.article')),
            ],
            options={
                'db_table': 'analytics_page_views',
                'indexes': [models.Index(fields=['date'], name='analytics_p_date_eab34d_idx'), models.Index(fields=['path'], name='analytics_p_path_76024a_idx'), models.Index(fields=['article', 'date'], name='analytics_p_article_bcd00d_idx')],
                'unique_together': {('url', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticsRealTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('current_page', models.URLField()),
                ('current_path', models.CharField(max_length=500)),
                ('referer', models.URLField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_realtime',
                'indexes': [models.Index(fields=['last_activity'], name='analytics_r_last_ac_911365_idx'), models.Index(fields=['session_id'], name='analytics_r_session_27e649_idx')],
            },
        ),
    ]
