# Generated by Django 6.0.5 on 2026-08-01 14:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'media_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_library.mediacategory')),
            ],
            options={
                'verbose_name_plural': 'Media Categories',
                'db_table': 'media_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to='media/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp', 'svg', 'mp4', 'webm', 'ogg', 'mp3', 'wav', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx'])])),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('other', 'Other')], max_length=20)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Image/Video width in pixels', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Image/Video height in pixels', null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds for video/audio', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('available', 'Available'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='uploading', max_length=20)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('thumbnail_small', models.ImageField(blank=True, null=True, upload_to='thumbnails/small/')),
                ('thumbnail_medium', models.ImageField(blank=True, null=True, upload_to='thumbnails/medium/')),
                ('thumbnail_large', models.ImageField(blank=True, null=True, upload_to='thumbnails/large/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaFileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='media_library.mediacategory')),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='media_library.mediafile')),
            ],
            options={
                'db_table': 'media_file_categories',
            },
        ),
        migrations.CreateModel(
            name='MediaFileTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='media_library.mediafile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='media_library.mediatag')),
            ],
            options={
                'db_table': 'media_file_tags',
            },
        ),
        migrations.CreateModel(
            name='MediaUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('field_name', models.CharField(max_length=100)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='media_library.mediafile')),
                ('used_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media_usages',
                'ordering': ['-used_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['file_type', 'status'], name='media_files_file_ty_d93a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='media_files_uploade_7a664a_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['file_hash'], name='media_files_file_ha_8ac706_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mediafilecategory',
            unique_together={('media_file', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='mediafiletag',
            unique_together={('media_file', 'tag')},
        ),
        migrations.AddIndex(
            model_name='mediausage',
            index=models.Index(fields=['media_file', 'model_name', 'object_id'], name='media_usage_media_f_4c3d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='mediausage',
            index=models.Index(fields=['used_at'], name='media_usage_used_at_74e891_idx'),
        ),
    ]
