# Generated by Django 6.0.5 on 2026-08-04 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='featured',
            field=models.BooleanField(default=False, help_text='Mark this media as featured for display on the homepage and galleries'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['featured'], name='media_files_feature_bba15c_idx'),
        ),
    ]
