# Generated by Django 6.0.5 on 2026-08-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for accessibility (screen readers)', max_length=500),
        ),
    ]
